spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss.SSS
    time-zone: GMT+8
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/manager?user=root&password=root&useUnicode=true&characterEncoding=utf-8
#    url: jdbc:h2:mem:manager;DB_CLOSE_ON_EXIT=FALSE
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    listener:
      simple:
        concurrency: 10
        max-concurrency: 10
        prefetch: 1
        default-requeue-rejected: true
    template:
      retry:
        enabled: true
        initial-interval: 1000
        max-attempts: 3
        max-interval: 10000
        multiplier: 1.0
  jpa:
    show-sql: true
server:
  port: 8081
  servlet-path: /manager
